sorcery:
  callback_url: "https://desktech-connect-ba757d0b0928.herokuapp.com/oauth/callback?provider=twitter"

default_url_options:
  protocol: 'https'
  host: 'desktech-connect-ba757d0b0928.herokuapp.com'